const heroesInit = [
  {
    name: "Elf",
    image: "elf.png",
    attack: 9,
    defense: 11,
    speed: 17,
  },
  {
    name: "Amazon",
    image: "amazon.png",
    attack: 12,
    defense: 12,
    speed: 15,
  },
  {
    name: "Barbarian",
    image: "barbarian.png",
    attack: 18,
    defense: 12,
    speed: 9,
  },
  {
    name: "Dark",
    image: "dark.png",
    attack: 11,
    defense: 12,
    speed: 16,
  },
  {
    name: "Druid",
    image: "druid.png",
    attack: 9,
    defense: 14,
    speed: 12,
  },
  {
    name: "Dwarf",
    image: "dwarf.png",
    attack: 13,
    defense: 13,
    speed: 16,
  },
  {
    name: "Fighter",
    image: "fighter.png",
    attack: 13,
    defense: 13,
    speed: 16,
  },
  {
    name: "Gladiator",
    image: "gladiator.png",
    attack: 18,
    defense: 9,
    speed: 12,
  },
  {
    name: "Hercules",
    image: "hercules.png",
    attack: 20,
    defense: 18,
    speed: 8,
  },
  {
    name: "Jedi Knight",
    image: "jediKnight.png",
    attack: 17,
    defense: 12,
    speed: 15,
  },
  {
    name: "Knight",
    image: "knight.png",
    attack: 18,
    defense: 14,
    speed: 13,
  },
  {
    name: "Monk",
    image: "elf.png",
    attack: 11,
    defense: 13,
    speed: 17,
  },
  {
    name: "Pirate",
    image: "pirate.png",
    attack: 12,
    defense: 12,
    speed: 14,
  },
  {
    name: "Ranger",
    image: "ranger.png",
    attack: 14,
    defense: 12,
    speed: 16,
  },
  {
    name: "Rogue",
    image: "rogue.png",
    attack: 16,
    defense: 14,
    speed: 17,
  },
  {
    name: "Samurai",
    image: "samurai.png",
    attack: 15,
    defense: 13,
    speed: 18,
  },
  {
    name: "Spartan",
    image: "spartan.png",
    attack: 16,
    defense: 14,
    speed: 16,
  },
  {
    name: "Thief",
    image: "pirate.png",
    attack: 15,
    defense: 16,
    speed: 18,
  },
  {
    name: "Warrior",
    image: "warrior.png",
    attack: 14,
    defense: 14,
    speed: 15,
  },
  {
    name: "Wizard",
    image: "wizard.png",
    attack: 12,
    defense: 16,
    speed: 14,
  },
];

export default heroesInit;
